url = 'https://www.bestbuy.com'
tests_dir = 'src.tests'
cfg_tests_dir = 'src.cfg.cfg_tests'
cfg_global_dir = 'src.cfg.cfg_global'
cfg_tests_dir = 'src.cfg.cfg_tests'
api_data_dir = 'src.api.rest_data'
search_term = 'hello'
phrase = 'hello kitty'
